### ISSUE TITLE
Node v16 support

### ISSUE THREAD

**Issue by untaggable** [untaggable/monoreact#826]
(node:28027) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/maxtarsis/personal/monoreact/node_modules/rollup-plugin-typescript2/node_modules/tslib/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by retarsis** [comment]
tracking
https://github.com/ezolenko/rollup-plugin-typescript2/issues/267

**Comment by untaggable** [comment]
probably fixed
https://github.com/ezolenko/rollup-plugin-typescript2/issues/267
